#!/bin/bash
set -eu
DATE=$(date '+%Y%m%d_%H%M')
jar=("./com.vaguehope.morrigan.dlna/target/com.vaguehope.morrigan.dlna-"*.jar)
echo "jar=$jar"
jarname="$(basename "$jar")"
echo "jarname=$jarname"
newname="${jarname%%.jar}-$DATE.jar"
echo "newname=$newname"
mv -v "$jar" "./com.vaguehope.morrigan.dlna/target/$newname"
